name: ecommerceapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # ---------------- UI / Design Related Packages ----------------
  cupertino_icons: ^1.0.8          # iOS-style icons
  google_fonts: ^6.2.1             # Custom fonts support from Google Fonts
  smooth_page_indicator: ^1.2.1    # Dots indicator for sliders/onboarding
  iconsax: ^0.0.8                  # Popular icon pack h
  readmore: ^3.0.0                 # Show more/show less text
  carousel_slider: ^5.0.0          # Image/content carousels
  flutter_rating_bar: ^4.0.1       # Star rating bars
  lottie: ^3.3.1                   # JSON-based animations
  shimmer: ^3.0.0                  # Skeleton loading effect for UI placeholders

  # ---------------- Data Handling / Logic / API ----------------
  http: ^1.3.0                     # REST API calls
  intl: ^0.20.2                    # Date/time formatting and localization
  get: ^4.7.2                      # State management, routing, and DI
  get_storage: ^2.1.1              # Local key-value storage
  connectivity_plus: ^6.1.4        # Internet connection checker

  # ---------------- Firebase / Backend Related ----------------
  firebase_core: ^3.13.0           # Base for all Firebase services
  firebase_auth: ^5.5.3            # User authentication via email and password
  cloud_firestore: ^5.6.7          # NoSQL cloud database
  firebase_storage: ^12.4.5        # Upload/store files like images
  google_sign_in: ^6.3.0           # User authentication via google

  # ---------------- Utilities / Miscellaneous ----------------
  logger: ^2.5.0                   # Logging for debugging
  url_launcher: ^6.3.1             # Launch external URLs, mail, phone
  flutter_native_splash: ^2.4.6    # Auto-generate native splash screens
  capped_progress_indicator: ^0.0.2 # Custom circular progress indicators



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/




